# Generated by Django 5.2.17 on 2026-10-04 17:45

import apps.resumes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.resumes.models.resume_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('parsed_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('uploaded', 'uploaded'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ai_analysis', models.JSONField(blank=True, default=dict)),
                ('analysis_status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
